# data config
dataset: winder-hybrids/medicaltextbook         # manually download the medical textbook corpus from the MedQA repo https://github.com/jind11/MedQA 
split: train
max_token_length: 2048

# model config
model: save/full_model_learned_context

# context config
context_type: none

# trainer config
batch_size: 16
accumulate_grad_batches: 1
max_epochs: 1
lr: 3e-5
warmup_ratio: 0.1
lr_scheduler: linear
gradient_clip_val: 1.0

# global config
mode: eval
seed: 1